### ISSUE TITLE
failed to connect to joplin port...

### ISSUE THREAD

**Issue by hicarl** [jerrylususu/joplin-vacuum#2]
如何连接上joplin GUI呢，出现错误
trying port 41184 not the port, skipping
trying port 41185 not the port, skipping
trying port 41186 not the port, skipping
trying port 41187 not the port, skipping
trying port 41188 not the port, skipping
trying port 41189 not the port, skipping
trying port 41190 not the port, skipping
trying port 41191 not the port, skipping
trying port 41192 not the port, skipping
trying port 41193 not the port, skipping
port not found
Traceback (most recent call last):
  File "vacuum.py", line 207, in <module>
    main(args)
  File "vacuum.py", line 143, in main
    raise Exception("failed to connect to joplin port...")
Exception: failed to connect to joplin port...

**Comment by jerrylususu** [comment]
Hi! 
- Please make sure you have enabled "Web Clipper" in Joplin settings.
- Have you tried to disable any running proxy software?

If it is still not working, can you share a screenshot of Joplin's web clipper setting page?

**Comment by hicarl** [comment]
非常感谢！Thank you very much！

**Comment by jerrylususu** [comment]
Closed due to no active response.
